#include <unary.h>


using namespace torch::nested_tensor;

//    (torch.abs, lambda input, out=None: -1),
//    (torch.acos, lambda input, out=None: -1),
//    (torch.angle, lambda input, out=None: -1),
//    (torch.asin, lambda input, out=None: -1),
//    (torch.atan, lambda input, out=None: -1),
//    (torch.bitwise_not, lambda input, out=None: -1),
//    (torch.ceil, lambda input, out=None: -1),
//    (torch.conj, lambda input, out=None: -1),
//    (torch.cos, lambda input, out=None: -1),
//    (torch.cosh, lambda input, out=None: -1),
//    (torch.digamma, lambda input, out=None: -1),
//    (torch.erf, lambda input, out=None: -1),
//    (torch.erfc, lambda input, out=None: -1),
//    (torch.erfinv, lambda input, out=None: -1),
//    (torch.exp, lambda input, out=None: -1),
//    (torch.expm1, lambda input, out=None: -1),
//    (torch.floor, lambda input, out=None: -1),
//    (torch.frac, lambda input, out=None: -1),
//    (torch.geqrf, lambda input, out=None: -1),
//    (torch.imag, lambda input, out=None: -1),
//    (torch.inverse, lambda input, out=None: -1),
//    (torch.lgamma, lambda input, out=None: -1),
//    (torch.log, lambda input, out=None: -1),
//    (torch.log10, lambda input, out=None: -1),
//    (torch.log1p, lambda input, out=None: -1),
//    (torch.log2, lambda input, out=None: -1),
//    (torch.logical_not, lambda input, out=None: -1),
//    (torch.max, lambda input, out=None: -1),
//    (torch.min, lambda input, out=None: -1),
//    (torch.neg, lambda input, out=None: -1),
//    (torch.real, lambda input, out=None: -1),
//    (torch.reciprocal, lambda input, out=None: -1),
//    (torch.round, lambda input, out=None: -1),
//    (torch.rsqrt, lambda input, out=None: -1),
//    (torch.sigmoid, lambda input, out=None: -1),
//    (torch.sign, lambda input, out=None: -1),
//    (torch.sin, lambda input, out=None: -1),
//    (torch.sinh, lambda input, out=None: -1),
//    (torch.sqrt, lambda input, out=None: -1),
//    (torch.tan, lambda input, out=None: -1),
//    (torch.tanh, lambda input, out=None: -1),
//    (torch.trunc, lambda input, out=None: -1),


